### ISSUE TITLE
[Feature] Fabric... maybe?

### ISSUE THREAD

**Issue by Haihatu** [SuperMartijn642/ConnectedGlass#27]
Idk if this will ever be an option and idk how much work this will need, but i think it would be cool to have a fabric vers.
i'd love to try this with my other fabric mods lol

**Comment by SuperMartijn642** [comment]
I am working on Fabric ports of all of my mods. Don't have too much time though, so they will be released *at some point*...

**Comment by Haihatu** [comment]
oh awesome! really like ur mod and cant wait lol

**Comment by Marceloooxx** [comment]
I would also use that im in search for something like this but in fabric, so im really interested. I have a world where i could use it, but i cant because im having problems with optifabric/optifine with mods crashing my game when loading in a world, so i excluded optifine, using now sodium, and waiting for this mod.

**Comment by Kasprenius** [comment]
I would also love a fabric version for this!!

**Comment by Emeraldog** [comment]
Same. Continuity's connected glass has so many rendering issues, especially in water. And that's not good for a guy who likes draining ocean monuments with glass walls surrounding them.
