### ISSUE TITLE
Unable to load models

### ISSUE THREAD

**Issue by NielsPilgaard** [SuperMartijn642/ConnectedGlass#3]
The latest.log is angry at your models, it would seem: https://gist.github.com/NillerMedDild/ec2d4109e4496206b97c4cad2596cebe#file-gistfile1-txt-L1118

**Comment by SuperMartijn642** [comment]
Yeah this seems to be a 1.13+ thing. I noticed most other mods just add dummy blockstate and model files, so I think I will just do the same.
Currently custom IBakedModels can only be added during the ModelBakeEvent, since vanilla doesn't use anything except json files, yet the errors already gets produced before that.

**Comment by NielsPilgaard** [comment]
Well that seems silly, I'll happilu take dummy files to suppress the log spam :P thanks for the quick response again!

**Comment by SuperMartijn642** [comment]
I added the dummy files in version 1.0.2, so the console spam is now gone 😁

**Comment by NielsPilgaard** [comment]
Thanks :D
