### ISSUE TITLE
[Crash] Server crashes saying Connected Glass requires Fusion, yet Fusion is present

### ISSUE THREAD

**Issue by bwiggin10** [SuperMartijn642/ConnectedGlass#60]
**Version Info**
- Minecraft - 1.12.2
- Connected Glass - Latest 1.1.11

Try to launch server with Connected Glass, Fusion + CoreLib and it crashes.
Able to launch from client without issue (Except when optifine is present, it crashes then too).
...

[crash-2024-02-12_00.02.18-server.txt](https://github.com/SuperMartijn642/ConnectedGlass/files/14234499/crash-2024-02-12_00.02.18-server.txt)

...

**Comment by SuperMartijn642** [comment]
That is rather odd. Fusion's core plugin appears to be loaded, but the mod itself is absent.
Could you provide the `latest.log` file as well?

**Comment by bwiggin10** [comment]
[2024-02-12-1.log](https://github.com/SuperMartijn642/ConnectedGlass/files/14234856/2024-02-12-1.log)
[2024-02-12-2.log](https://github.com/SuperMartijn642/ConnectedGlass/files/14234857/2024-02-12-2.log)

Broken up into two parts because thats the way it's displayed to me.

Edit: Initially uploaded .gz versions, re-uploaded just the .log

**Comment by SuperMartijn642** [comment]
![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/12382965/d135319a-5822-4ebb-8a9a-e8e7e4616fa9)
Whelp that would be why I guess. For some reason I didn't actually consider the fact that this is about a server 😅
Turns out I just marked the dependency incorrectly as it should be client-only.

It should be fixed now in Connected Glass version 1.1.11a for Minecraft 1.12.
Thank you for reporting the issue!
