### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by CrimboJimbo** [SuperMartijn642/ConnectedGlass#61]
**Version Info**
- Minecraft, 1.18.2
- Connected Glass, 1.1.11

**Description of the Bug**
Advancement title not displaying properly
connectedglass.advancement.recipes/connectedglass/borderless_glass1.title
connectedglass.advancement.recipes/connectedglass/borderless_glass_pane1.title

**Steps to Reproduce**
Craft glass and/or Glass panes

**Screenshots**
![javaw_P2oITopCfC](https://github.com/SuperMartijn642/ConnectedGlass/assets/88461252/38d7052a-27db-4402-959d-6888d2d32e4c)

**Comment by SuperMartijn642** [comment]
Wut, those are just advancements to grant the recipes. Those advancements should never be displayed. Even vanilla's recipe advancements don't have titles.

Do you have some other mod which puts those advancements in chat?

**Comment by CrimboJimbo** [comment]
Not from what I can tell. We have been using this server for a while now and that is the only time I've seen those messages I've seen like that. Would you like me to send the entire mod list?

**Comment by SuperMartijn642** [comment]
I just tested it to make sure and the only thing that pops up is the toast in the top right, like it is for any recipe advancement.
Thus it is likely caused by another mod you have installed.

> Would you like me to send the entire mod list?

It is too much effort for me to download and filter out mods to find which mod causes the issue. If you want to, you can narrow down which other mod causes it and I'll see if it's something to be fixed on their end or on mine. If not, I'll close the issue as it's likely to just be caused by some other mod.

**Comment by CrimboJimbo** [comment]
Interesting. I'll look through and see what I can find. Thank You!
