### ISSUE TITLE
[Feature] Allow connected textures between different types/colors

### ISSUE THREAD

**Issue by MemeKueen2** [SuperMartijn642/ConnectedGlass#64]
**Is your feature request related to a problem? Please describe.**
Currently the different types of glass (borderless, clear, scratched) and colors do not connect to one another. I really like the clear glass, but I'd like to texture it with scratched or borderless in spots for added aesthetic/visibility. And if done with types, might as well do it with colors too to allow for seamless color changes, which would be useful when creating large stained glass windows

![image](https://github.com/SuperMartijn642/ConnectedGlass/assets/139596661/486e8d21-7ac1-4aeb-9087-d7f85a037a84)

**Describe the solution you'd like**
Allow different types/colors to connect to other types/colors without borders for seamless transition. This could also be implemented through config/settings so users can choose whether they want types and/or colors to connect or leave it as is.

**Comment by SuperMartijn642** [comment]
Whether the different blocks should connect to each other is mostly personal preference.

> This could also be implemented through config/settings so users can choose whether they want types and/or colors to connect or leave it as is.

My main reason for Connected Glass adding new blocks rather than changing the vanilla blocks, is to make it so blocks look the same for all players. Having it be configurable would somewhat go against that.
Besides that, it is also just not something that's not very easy to implement through a config option as what the blocks connect to is defined through a resource pack. Spending the time to work on something like that most people won't use just doesn't seem worth it to me.

That being said, you could simply create a resource pack yourself to overwrite Connected Glass' model files and add additional connections. All of the resources for Connected Glass' models can be found here https://github.com/SuperMartijn642/ConnectedGlass/tree/fabric-1.20.3/src/generated/resources/assets/connectedglass/models.
And documentation for the connections can be found on Fusion's wiki.
