### ISSUE TITLE
Forge Tag Suggestions

### ISSUE THREAD

**Issue by TheBedrockMaster** [SuperMartijn642/ConnectedGlass#74]
**Describe the solution you'd like**

I would love it if stained glass from this mod got the forge:glass/colored item tag and if each colour got the forge:glass/(specific colour) item tags.

**Comment by SuperMartijn642** [comment]
I cannot find any reference to a `forge:glass/colored` tag. There are the `forge:glass/colorless` and `forge:stained_glass` tags which the glass is already added to.

> if each colour got the forge:glass/(specific colour) item tags.

Not sure how, but I just completely missed these tags. I don't remember ever even seeing these tags, but apparently they've been there since 1.14.

I've added the glass blocks and items to the `forge:glass/color` tags now in Connected Glass version 1.1.12.
Thank you for reporting the issue!
